ERR_MSG_MAP.set('100', 'invalid_request_scheme 错误的请求协议');
ERR_MSG_MAP.set('101', 'invalid_request_method 错误的请求方法');
ERR_MSG_MAP.set('102', 'access_token_is_missing 未找到 access_token');
ERR_MSG_MAP.set('103', 'invalid_access_token access_token 不存在或已被用户删除，或者用户修改了密码');
ERR_MSG_MAP.set('104', 'invalid_apikey apikey 不存在或已删除');
ERR_MSG_MAP.set('105', 'apikey_is_blocked apikey 已被禁用');
ERR_MSG_MAP.set('106', 'access_token_has_expired access_token 已过期');
ERR_MSG_MAP.set('107', 'invalid_request_uri 请求地址未注册');
ERR_MSG_MAP.set('108', 'invalid_credencial1 用户未授权访问此数据');
ERR_MSG_MAP.set('109', 'invalid_credencial2 apikey 未申请此权限');
ERR_MSG_MAP.set('110', 'not_trial_user 未注册的测试用户');
ERR_MSG_MAP.set('111', 'rate_limit_exceeded1 用户访问速度限制');
ERR_MSG_MAP.set('112', 'rate_limit_exceeded2 IP 访问速度限制');
ERR_MSG_MAP.set('113', 'required_parameter_is_missing 缺少参数');
ERR_MSG_MAP.set('114', 'unsupported_grant_type 错误的 grant_type');
ERR_MSG_MAP.set('115', 'unsupported_response_type 错误的 response_type');
ERR_MSG_MAP.set('116', 'client_secret_mismatch client_secret不匹配');
ERR_MSG_MAP.set('117', 'redirect_uri_mismatch redirect_uri不匹配');
ERR_MSG_MAP.set('118', 'invalid_authorization_code authorization_code 不存在或已过期');
ERR_MSG_MAP.set('119', 'invalid_refresh_token refresh_token 不存在或已过期');
ERR_MSG_MAP.set('120', 'username_password_mismatch 用户名密码不匹配');
ERR_MSG_MAP.set('121', 'invalid_user 用户不存在或已删除');
ERR_MSG_MAP.set('122', 'user_has_blocked 用户已被屏蔽');
ERR_MSG_MAP.set('123', 'access_token_has_expired_since_password_changed 因用户修改密码而导致 access_token 过期');
ERR_MSG_MAP.set('124', 'access_token_has_not_expired access_token 未过期');
ERR_MSG_MAP.set('125', 'invalid_request_scope 访问的 scope 不合法，开发者不用太关注，一般不会出现该错误');
ERR_MSG_MAP.set('126', 'invalid_request_source 访问来源不合法');
ERR_MSG_MAP.set('127', 'thirdparty_login_auth_faied 第三方授权错误');
ERR_MSG_MAP.set('128', 'user_locked 用户被锁定');
ERR_MSG_MAP.set('999', 'unknown 未知错误');
